name = "openai"                # todo
main = "index.js"
compatibility_date = "2024-05-06"

[ai]
binding = "AI" # i.e. available in your Worker on env.AI

[vars]
CLOUDFLARE_ACCOUNT_ID = "9571ff91774865cafe98796b85911d3b" # replace with your own.
# MODEL_MAPPER = { "gpt-3.5-turbo" = "@cf/meta/llama-2-7b-chat-int8" } # Optional
